name: Premier Workflow

# Déclencheur : quand exécuter ce workflow ?
on: [push]

# Un workflow contient un ou plusieurs jobs
jobs:
  # Nom de notre job
  dire-bonjour:
    # Sur quel système d'exploitation exécuter ce job ?
    runs-on: ubuntu-latest

    # Liste des étapes à exécuter dans ce job
    steps:
      - name: Etape 1
        run: echo "Bonjour classe ICT324 !"

      - name: Etape 2
        run: echo "Ceci est mon premier workflow automatisé."

      - name: Etape 3
        run: echo "Fin du workflow."